[workspace]
resolver = "2"

members = [
    "pipecast-playground",
    "pipecast-pipewire", "pipecast-ipc", "pipecast-shared", "pipecast-client", "pipecast-daemon",
]

[workspace.dependencies]
### Error Handling ###
anyhow = "1.0.95"

### Serialisation / Deserialisation ###
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"

### JSON Patching ###
json-patch = "3.0.1"

### IPC Communication ###
interprocess = { version = "2.2.1", features = ["tokio"] }