[workspace]
resolver = "2"

members = [
    "pipecast-client",
    "pipecast-daemon",
    "pipecast-ipc",
    "pipecast-pipewire",
    "pipecast-playground",
    "pipecast-profile",
    "pipecast-shared",
]

[workspace.dependencies]
### Logging ###
log = "0.4.25"

### Error Handling ###
anyhow = "1.0.95"

### Serialisation / Deserialisation ###
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"

### JSON Patching ###
json-patch = "3.0.1"

### IPC Communication ###
interprocess = { version = "2.2.1", features = ["tokio"] }

### Device Identification ###
ulid = "1.2.0"
