[package]
name = "pipecast-profile"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
ulid = { workspace = true }

enum-map = "2.7.3"

strum = "0.27.0"
strum_macros = "0.27.0"