[package]
name = "pipecast-pipewire"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.93", features = ["backtrace"] }
log = "0.4.22"

pipewire = { git = "https://gitlab.freedesktop.org/FrostyCoolSlug/pipewire-rs.git" }
oneshot = "0.1.8"

ulid = "1.1.4"